### ISSUE TITLE
build broken (by eslint integration)

### ISSUE THREAD

**Issue by maxkoryukov** [maxkoryukov/tndr#17]
enh #14 cause break a build. need to fffix

**Comment by maxkoryukov** [comment]
https://travis-ci.org/maxkoryukov/tndr/builds/122668960

**Comment by maxkoryukov** [comment]
```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open 'dev/jslint-report/client.html'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
```
